# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0c18279c8f4d1054f955f814b884796bfe569bdb45bc411be8d95c65eca0d065d60b75365efced7d9ba7f97dc2267181e6a132bc8fa396ecaa631aa598aa1792

test:
  secret_key_base: cd6aac3d664abbdcfaa9e8602c569a028b1c9e9bcbf782ba0e0e22e8e2cf58abb5e64bb034372430e4c427fe1cbc653a595d9e4048bb31e2700042e47aa03c04

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
